// app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ClientProviders from "@/components/ClientProviders";
import axios from "axios";
import { useSession } from "next-auth/react";
import "@mantine/core/styles.css";
import { createTheme, MantineProvider } from "@mantine/core";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "DOIT",
  description: "Generated by create next app",
};

// axios.interceptors.request.use(
//   (config) => {
//     const { data: session } = useSession();

//     const token = session?.user.token;

//     if (token) {
//       config.headers.Authorization = `Bearer ${token}`;
//     }

//     return config;
//   },
//   (error) => {
//     return Promise.reject(error);
//   }
// );

// axios.interceptors.response.use(
//   (config) => {
//     return config;
//   },
//   (error) => {
//     if (error.response) {
//       if (error.response.status === 401) {
//         // sign user out
//       }
//     }
//   }
// );
const theme = createTheme({
  /** Put your mantine theme override here */
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientProviders>
          <MantineProvider theme={theme}>{children}</MantineProvider>
        </ClientProviders>
      </body>
    </html>
  );
}
